package com.sssemion.calculator.calc;

public enum KeyType {
    EQUALS, PLUS, MINUS, MULTIPLY, DIVIDE, PERCENT, POWER, ROOT, DECIMAL, CLEAR, RESET, FACTORIAL,

    DIGIT, ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE
}
